002 normalise graph
patrickemoore/angel-investing-simulations pull request #12
Opened 2023-09-07 09:42 UTC by aknipey

Added normalise and percent change sliders, with corresponding axis name changes
![Screenshot from 2023-09-07 19-17-44](https://github.com/patrickemoore/angel-investing-simulations/assets/134905175/53cefbc6-20ad-4396-a42b-ff9ed7e8ff8c)

2023-09-07 22:30 UTC, patrickemoore requested changes
almost lgtm, but need to streamline the normalisation and scaling math. Performance is a reasonably big concern for the 1000 simuations.

2023-09-07 22:30 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
This is very hacky. I think we can represent this as linear transformation. So we should apply the normalisation if it is normalised, then apply the scaling. Whatever it is, this case bash should be simplified.

2023-09-07 22:30 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
Also extract helper functions, these might be useful later

2023-09-07 22:30 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +        y: outcome.map(portfolioState => {
As above

2023-09-07 22:30 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +            </Stack>
This indentation is off, does eslint not pick this up?

2023-09-07 22:30 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
(btw defining helper functions as constants in the global scope is much more efficient in react as react doesn't have to recalculate the function every time)

2023-09-07 22:40 UTC, aknipey commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
Oh ok yeah ill do that. Ill put a function in utils
Are there inbuilt tools for linear transformations or do i need a library

2023-09-07 22:44 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
just do the maths yourself

if (normalised) normalise();
if (scaled) scale();

2023-09-07 22:45 UTC, aknipey commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
yep thats what i started doing ok cool

2023-09-07 22:46 UTC, aknipey commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
oh this is actually so much easier

2023-09-08 05:29 UTC, patrickemoore approved these changes

2023-09-08 05:55 UTC, merged