003 information tooltips
patrickemoore/angel-investing-simulations pull request #13
Opened 2023-09-07 14:02 UTC by aknipey

Poor quality content of the actual information. Need to improve before actually merged in. Please help, especially on the coin-toss feature (couldnt be bothered to figure out the maths its easier to ask you)
![Screenshot from 2023-09-08 00-01-30](https://github.com/patrickemoore/angel-investing-simulations/assets/134905175/3544011a-0dd2-42dc-ac78-fb2267c840d4)

2023-09-07 22:38 UTC, patrickemoore commented
We will iterate on this. For now have a look at https://mui.com/material-ui/react-floating-action-button/ and replace the button

2023-09-08 02:41 UTC, patrickemoore requested changes

2023-09-08 02:41 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +  const GRAPH_LAYOUT = useMemo(() => {
THIS_NAMING_SCHEME is only for global scope constants, useThisOneInstead for in-component constants

2023-09-08 02:41 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +    }
construct the title in 3 parts, the "Portfolio Value", "Change" and "$" or "%". Also factor out the y = {}

2023-09-08 02:41 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +    },
Define this as global constant and spread it

2023-09-08 02:41 UTC, patrickemoore commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
Extract into additional functions

2023-09-08 02:47 UTC, aknipey commented on frontend/src/components/OutcomeGraph.tsx
> +        }),
already done in 002

2023-09-08 02:51 UTC, aknipey commented on frontend/src/components/OutcomeGraph.tsx
> +  const GRAPH_LAYOUT = useMemo(() => {
i may have copied that scheme in more spots bc this particular one was already in the code. Will change

2023-09-08 05:30 UTC, patrickemoore approved these changes

2023-09-08 05:30 UTC, patrickemoore approved these changes

2023-09-11 05:33 UTC, patrickemoore commented on frontend/src/components/ParameterInput.tsx
> +            </Stack>
This will have to be improved

2023-09-11 05:33 UTC, patrickemoore approved these changes
lgtm, see inline

2023-09-11 05:33 UTC, merged